Install socketio
tigerscave/falcon-svelte-camera-viewer pull request #14
Opened 2023-02-14 08:59 UTC by falconkun

#13

2023-02-14 09:04 UTC, azamiya requested changes

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  // client-side
いらないコメントは消そう

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +    console.log("---connected---")
いらない `console.log`は消そう

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  //ping-check
コメントいる？

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  function ping_insert(ping_value){
jsの関数はキャメルケースで統一しよう
関数名が宜しくない　pingInsert とは？？？

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  let ping_view = ''
jsでは変数名はcamelCaseにしよう
ping_viewってなんじゃ？
せめてpingTextとか、pingResultTextとかにしよう

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  import { io } from "socket.io-client";
これ、上の３行目くらいに持ってこよう
importはimportでまとめないと、後々こんがらがる

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +      return ping_view = '0'
stringにする必要ある？

2023-02-14 09:04 UTC, azamiya commented on src/App.svelte
> +  function trigger(){
triggerって何？なんのtrigger？

2023-02-14 09:31 UTC, rhmtrz commented on src/App.svelte
> +      console.log(pingResultText)
please remove the `console.log()`

2023-02-14 09:34 UTC, rhmtrz approved these changes

2023-02-16 09:56 UTC, azamiya approved these changes

2023-02-16 09:56 UTC, merged